//
//  StyleKitName.swift
//  ProjectName
//
//  Created by Luke Regan on 9/10/15.
//  Copyright (c) 2015 LReganCG. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

open class StyleKitName : NSObject {

    //// Drawing Methods

    open class func drawCanvas1(_ progressAmmount: CGFloat) {
        //// Color Declarations
        let color = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 0.332)

        //// Variable Declarations
        let expression: CGFloat = progressAmmount * 297

        //// overlay Drawing
        let overlayPath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: expression, height: 95))
        color.setFill()
        overlayPath.fill()
    }

}

open class workoutsProgressOverlay : NSObject {
	
	//// Drawing Methods
	
	open class func drawCanvas1(_ progressAmmount: CGFloat) {
		//// Color Declarations
		let color = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 0.332)
		
		//// Variable Declarations
		let expression: CGFloat = progressAmmount * 264
		
		//// overlay Drawing
		let overlayPath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: expression, height: 72))
		color.setFill()
		overlayPath.fill()
	}
	
}

@objc protocol StyleKitSettableImage {
    func setImage(_ image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(_ image: UIImage!)
}
