//
//  StyleKitName.swift
//  ProjectName
//
//  Created by Luke Regan on 9/10/15.
//  Copyright (c) 2015 LReganCG. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKitName : NSObject {

    //// Drawing Methods

    public class func drawCanvas1(progressAmmount: CGFloat) {
        //// Color Declarations
        let color = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 0.332)

        //// Variable Declarations
        let expression: CGFloat = progressAmmount * 297

        //// overlay Drawing
        let overlayPath = UIBezierPath(rect: CGRectMake(0, 0, expression, 95))
        color.setFill()
        overlayPath.fill()
    }

}

public class workoutsProgressOverlay : NSObject {
	
	//// Drawing Methods
	
	public class func drawCanvas1(progressAmmount: CGFloat) {
		//// Color Declarations
		let color = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 0.332)
		
		//// Variable Declarations
		let expression: CGFloat = progressAmmount * 264
		
		//// overlay Drawing
		let overlayPath = UIBezierPath(rect: CGRectMake(0, 0, expression, 72))
		color.setFill()
		overlayPath.fill()
	}
	
}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
